# presence test 

# this is the first working version 
# alas lis_ph looses wifi connection ... must test this further 

# i could do this in 2 parts ....
# ----------------------------------------------------
# part one fat light with random off time
# part two dimmer light with random off time 
# ie. after 22:00 ...

# this is the version with a time pattern ...
- alias: Simulate presence
  trigger:
    - platform: time_pattern
      # minutes: '/1'
      seconds: '/10'
  condition:  
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.vz_light_daytime
        state: 'evening'
      - condition: state
        entity_id: 'group.people'
        state: 'not_home'
      - condition: state
        entity_id: 'input_select.presenceenabled'
        state: 'True'
      - condition: numeric_state
        entity_id:  input_number.pres_counter # must change this to counter.pres_counter !!
        above: 0 # need some value here !
      - condition: numeric_state
        entity_id:  input_number.pres_counter # must change this to counter.pres_counter !!
        below: 2 # need some value here !
  action:
  - service: script.turn_on
    entity_id: script.lightspresence

# TEST ONLY for debug
- alias: Simulate presence2
  trigger:
    - platform: time_pattern
      # minutes: '/1'
      seconds: '/10'
  condition:  
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.vz_light_daytime
        state: 'day'
      - condition: state
        entity_id: 'group.people'
        state: 'home'
      - condition: state
        entity_id: 'input_select.presenceenabled'
        state: 'True'
      - condition: numeric_state
        entity_id:  input_number.pres_counter # must change this to counter.pres_counter !!
        above: 0 # need some value here !
      - condition: numeric_state
        entity_id:  input_number.pres_counter # must change this to counter.pres_counter !!
        below: 2 # need some value here !
  action:
  - service: script.turn_on
    entity_id: script.lightspresence


#    _____ _______ _____                _                        _   _
#   / ____|__   __|  __ \              | |                      | | (_)
#  | (___    | |  | |  | |   __ _ _   _| |_ ___  _ __ ___   __ _| |_ _  ___  _ __
#   \___ \   | |  | |  | |  / _` | | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \
#   ____) |  | |  | |__| | | (_| | |_| | || (_) | | | | | | (_| | |_| | (_) | | | |
#  |_____/   |_|  |_____/   \__,_|\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|




- alias: Hijacked Hue Dimmer Automations
  trigger:
    platform: state
    entity_id: sensor.buttonevent
  action:
  - service: persistent_notification.create
    data_template:
      message: >
        {% if states.sensor.living_room_remote_status.state == "1" %}
        'Button 1 pressed'
        {% elif states.sensor.living_room_remote_status.state == "2" %}
        'Button 2 pressed'
        {% elif states.sensor.living_room_remote_status.state == "3" %}
        'Button 3 pressed'
        {% elif states.sensor.living_room_remote_status.state == "4" %}
        'Button 4 pressed'
        {% else %}
        none
        {% endif %}


- alias: FULL Hijacked Hue Dimmer Automations
  trigger:
    platform: state
    entity_id: sensor.buttonevent
  action:
  - service: persistent_notification.create
    data_template:
      message: >
        {% if states.sensor.full_living_room_remote_status.state == "1001" %}
        'Button 1001 pressed'
        {% elif states.sensor.full_living_room_remote_status.state == "2001" %}
        'Button 2001 pressed'
        {% elif states.sensor.full_living_room_remote_status.state == "3001" %}
        'Button 3001 pressed'
        {% elif states.sensor.full_living_room_remote_status.state == "4001" %}
        'Button 4001 pressed'
        {% else %}
        none 001
        {% endif %}



#   _____       _   _                               _                        _   _
#  |  __ \     | | | |                             | |                      | | (_)
#  | |__) |   _| |_| |__   ___  _ __     __ _ _   _| |_ ___  _ __ ___   __ _| |_ _  ___  _ __
#  |  ___/ | | | __| '_ \ / _ \| '_ \   / _` | | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \
#  | |   | |_| | |_| | | | (_) | | | | | (_| | |_| | || (_) | | | | | | (_| | |_| | (_) | | | |
#  |_|    \__, |\__|_| |_|\___/|_| |_|  \__,_|\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|
#          __/ |
#         |___/

- alias: Python Hijacked automation
  trigger:
  - entity_id: sensor.dimmerbuttonevent
    platform: state  
  - entity_id: sensor.dimmerlastupdated
    platform: state
  action:
  - service: python_script.hue_dimmer
